day = 1;
plotSEM(seqActComb{day}(rewCellsComb{day},:)')
hold on
plotSEM(seqActComb{6}(rewCellsComb{6},:)')
line([10 10],get(gca,'ylim'),'color','k')
line([40 40],get(gca,'ylim'),'color','k')
line([70 70],get(gca,'ylim'),'color','k')
line([100 100],get(gca,'ylim'),'color','k')
line([130 130],get(gca,'ylim'),'color','k')
line([150 150],get(gca,'ylim'),'color','b')
line([180 180],get(gca,'ylim'),'color','r')
title('Puff Cells Response')
xlabel('Frame')
ylabel('dF/F')
legend({'Day 6','Day 1'})